/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.veiculo;

import controller.ControllerVeiculo;
import entidade.Veiculo;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.VeiculoModel;

/**
 *
 * @author Weskley
 */
public class FormListaVeiculo extends javax.swing.JDialog {

    /**
     * Creates new form FormListaVeiculo
     */
    public FormListaVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbVeiculos = new javax.swing.JTable();
        btAlterarVeiculo = new javax.swing.JButton();
        btCadVeiculo = new javax.swing.JButton();
        btExcluirVeiculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listagem dos Veículos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tbVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbVeiculos);

        btAlterarVeiculo.setText("Alterar");
        btAlterarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarVeiculoActionPerformed(evt);
            }
        });

        btCadVeiculo.setText("Cadastrar");
        btCadVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadVeiculoActionPerformed(evt);
            }
        });

        btExcluirVeiculo.setText("Excluir");
        btExcluirVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirVeiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCadVeiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAlterarVeiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExcluirVeiculo))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAlterarVeiculo)
                    .addComponent(btCadVeiculo)
                    .addComponent(btExcluirVeiculo))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        carregarVeiculos();
    }//GEN-LAST:event_formWindowActivated

    private void btCadVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadVeiculoActionPerformed
        new FormCadastro().setModal(true);
        new FormCadastro().setVisible(true);
    }//GEN-LAST:event_btCadVeiculoActionPerformed

    private void btExcluirVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirVeiculoActionPerformed
        if (tbVeiculos.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione algum registro");
        } else {
            if (JOptionPane.showConfirmDialog(rootPane, "Confirma a exclusão do veículo?") == 0) {
                new VeiculoModel().excluir((Long) tbVeiculos.getValueAt(tbVeiculos.getSelectedRow(), 0));
            }
        }
    }//GEN-LAST:event_btExcluirVeiculoActionPerformed

    private void btAlterarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarVeiculoActionPerformed
        if (tbVeiculos.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione algum registro");
        } else {
            FormCadastro fc = new FormCadastro();
            fc.v.setId((Long) tbVeiculos.getValueAt(tbVeiculos.getSelectedRow(), 0));
            fc.v.setModelo((String) tbVeiculos.getValueAt(tbVeiculos.getSelectedRow(), 1));
            fc.v.setFabricante((String) tbVeiculos.getValueAt(tbVeiculos.getSelectedRow(), 2));
            fc.v.setAno((Integer) tbVeiculos.getValueAt(tbVeiculos.getSelectedRow(), 3));
            fc.v.setPreco((Double) tbVeiculos.getValueAt(tbVeiculos.getSelectedRow(), 4));
            fc.status = "Alterar";
            fc.setTitle("Alterar Veículo");
            fc.setModal(true);
            fc.setVisible(true);
        }
    }//GEN-LAST:event_btAlterarVeiculoActionPerformed
    private void carregarVeiculos() {
        try {
            tbVeiculos.setModel(new DefaultTableModel(new Object[][]{}, new String[]{"Código", "Modelo", "Fabricante", "Ano", "Valor"}));
            DefaultTableModel rows = (DefaultTableModel) tbVeiculos.getModel();
            for (Veiculo v : new ControllerVeiculo().getVeiculos()) {
                rows.addRow(new Object[]{v.getId(), v.getModelo(), v.getFabricante(), v.getAno(), v.getPreco()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao carregar os dados: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormListaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormListaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormListaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormListaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormListaVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarVeiculo;
    private javax.swing.JButton btCadVeiculo;
    private javax.swing.JButton btExcluirVeiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbVeiculos;
    // End of variables declaration//GEN-END:variables
}
