/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JDialog;
import view.veiculo.FormCadastro;
import view.veiculo.FormListaVeiculo;

/**
 *
 * @author Weskley
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnMenu = new javax.swing.JMenu();
        mnAbrirVeiculos = new javax.swing.JMenu();
        mnAbrirVeiculosCadastro = new javax.swing.JMenuItem();
        mnAbrirVeiculosLista = new javax.swing.JMenuItem();
        mnSistema = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Veículos");

        mnMenu.setText("Abrir");

        mnAbrirVeiculos.setText("Veículos");

        mnAbrirVeiculosCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnAbrirVeiculosCadastro.setText("Cadastro");
        mnAbrirVeiculosCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAbrirVeiculosCadastroActionPerformed(evt);
            }
        });
        mnAbrirVeiculos.add(mnAbrirVeiculosCadastro);

        mnAbrirVeiculosLista.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnAbrirVeiculosLista.setText("Lista");
        mnAbrirVeiculosLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAbrirVeiculosListaActionPerformed(evt);
            }
        });
        mnAbrirVeiculos.add(mnAbrirVeiculosLista);

        mnMenu.add(mnAbrirVeiculos);

        jMenuBar1.add(mnMenu);

        mnSistema.setText("Sistema");
        jMenuBar1.add(mnSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnAbrirVeiculosCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAbrirVeiculosCadastroActionPerformed
        formOpen(new FormCadastro());
    }//GEN-LAST:event_mnAbrirVeiculosCadastroActionPerformed

    private void mnAbrirVeiculosListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAbrirVeiculosListaActionPerformed
        formOpen(new FormListaVeiculo());
    }//GEN-LAST:event_mnAbrirVeiculosListaActionPerformed
    private void formOpen(JDialog form) {
        form.setModal(true);
        form.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnAbrirVeiculos;
    private javax.swing.JMenuItem mnAbrirVeiculosCadastro;
    private javax.swing.JMenuItem mnAbrirVeiculosLista;
    private javax.swing.JMenu mnMenu;
    private javax.swing.JMenu mnSistema;
    // End of variables declaration//GEN-END:variables
}
